spring:
  datasource:
    jdbc-url=jdbc: mysql://localhost:3306/babaytun?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1973
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8090

netty:
  host: 127.0.0.1
  port: 9090
